{
  "extends": ["eslint:recommended", "prettier"],
  "plugins": ["prettier", "jest"],
  "rules":
    {
      "prettier/prettier": ["error"],
      "indent": ["error", 2],
      "require-jsdoc": 0,
      "no-console": ["error"]
    },
  "parserOptions": { "ecmaVersion": 2018 },
  "env": { "es6": true, "node": true, "jest/globals": true }
}
